<a href="https://colab.research.google.com/github/povashraful/SOTA-Implementation/blob/main/Large%20Language%20Model%20from%20Scratch/Token_Embedding_Demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Word2Vec - by Google

Word2Vec (pre-trained trained on a part of the Google News dataset (about 100 billion words). The model contains 3-- dimensional vectors for 3 million words and phrases. ) - source Hugging Face

In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 78.3 MB/s eta 0:00:00


In [ ]:
import gensim.downloader as api

In [ ]:
model = api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


Example of a word -represented as a vector

In [ ]:
#let us now see how the vector embedding of a word looks like

word_vectors = model


# Example: Accessing the vector for the word 'computer'
print(word_vectors['computer'])

[ 1.07421875e-01 -2.01171875e-01  1.23046875e-01  2.11914062e-01
 -9.13085938e-02  2.16796875e-01 -1.31835938e-01  8.30078125e-02
  2.02148438e-01  4.78515625e-02  3.66210938e-02 -2.45361328e-02
  2.39257812e-02 -1.60156250e-01 -2.61230469e-02  9.71679688e-02
 -6.34765625e-02  1.84570312e-01  1.70898438e-01 -1.63085938e-01
 -1.09375000e-01  1.49414062e-01 -4.65393066e-04  9.61914062e-02
  1.68945312e-01  2.60925293e-03  8.93554688e-02  6.49414062e-02
  3.56445312e-02 -6.93359375e-02 -1.46484375e-01 -1.21093750e-01
 -2.27539062e-01  2.45361328e-02 -1.24511719e-01 -3.18359375e-01
 -2.20703125e-01  1.30859375e-01  3.66210938e-02 -3.63769531e-02
 -1.13281250e-01  1.95312500e-01  9.76562500e-02  1.26953125e-01
  6.59179688e-02  6.93359375e-02  1.02539062e-02  1.75781250e-01
 -1.68945312e-01  1.21307373e-03 -2.98828125e-01 -1.15234375e-01
  5.66406250e-02 -1.77734375e-01 -2.08984375e-01  1.76757812e-01
  2.38037109e-02 -2.57812500e-01 -4.46777344e-02  1.88476562e-01
  5.51757812e-02  5.02929

In [ ]:
print(word_vectors['computer'].shape)

# trying to how many dimensions do we have

(300,)


Let us now see if vector embedding captures semantic meaning or not!

King + Woman - Man = ?

In [ ]:
# Example of using most_similar

results = word_vectors.most_similar(
    positive=['king', 'woman'],
    negative=['man'],
    topn=18
)

print(f"{'Word':<25} {'Similarity':>10}")
print("-" * 37)

for word, score in results:
    print(f"{word:<25} {score:>10.4f}")


Word                      Similarity
-------------------------------------
queen                         0.7118
monarch                       0.6190
princess                      0.5902
crown_prince                  0.5499
prince                        0.5377
kings                         0.5237
Queen_Consort                 0.5236
queens                        0.5181
sultan                        0.5099
monarchy                      0.5087
royal_palace                  0.5087
throne                        0.5006
royal                         0.4938
Princess_Sikhanyiso           0.4937
ruler                         0.4909
empress                       0.4888
Prince_Paras                  0.4833
princes                       0.4811


In [ ]:
#let us now see how the vector embedding of a word looks like

word_vectors2 = model


# Example: Accessing the vector for the word 'computer'
print(word_vectors['Human'])

[ 1.10839844e-01  3.44238281e-02  4.39453125e-01  1.74804688e-01
 -1.37695312e-01  2.80761719e-02  7.76367188e-02  8.64257812e-02
  9.70458984e-03  1.56250000e-01  6.05468750e-02  1.94335938e-01
  7.27539062e-02 -1.90429688e-01  3.22265625e-02 -2.10937500e-01
  1.91406250e-01  8.98437500e-02 -2.37304688e-01  2.23632812e-01
 -1.14746094e-01 -4.63867188e-02  7.08007812e-02  1.83593750e-01
  7.71484375e-02 -1.92382812e-01 -2.51953125e-01 -4.00390625e-02
  3.47656250e-01 -2.46093750e-01 -3.57421875e-01  1.53320312e-01
 -1.27929688e-01 -1.30859375e-01 -3.67187500e-01  1.07421875e-01
 -9.86328125e-02  1.49414062e-01 -1.62109375e-01 -6.83593750e-02
 -1.61743164e-03  2.65625000e-01 -2.09960938e-01  4.96093750e-01
 -1.72851562e-01  2.35351562e-01 -1.18164062e-01  2.67578125e-01
 -4.05273438e-02  8.30078125e-02 -1.19628906e-01 -6.59179688e-02
 -3.26171875e-01 -2.95639038e-04  4.76074219e-03 -5.17578125e-02
 -1.19140625e-01 -4.14062500e-01 -3.41796875e-02  3.06640625e-01
  5.41992188e-02  1.52343

In [ ]:
# Example of using most_similar

results = word_vectors.most_similar(
    positive=['Ape', 'Mon'],
    negative=['Spirit'],
    topn=18
)

print(f"{'Word':<25} {'Similarity':>10}")
print("-" * 37)

for word, score in results:
    print(f"{word:<25} {score:>10.4f}")


Word                      Similarity
-------------------------------------
Thu                           0.4896
Tue                           0.4844
Fri                           0.4718
Wed                           0.4688
Sat                           0.4646
Thur                          0.4286
marx                          0.4039
Jei                           0.4007
Art_Gallerie                  0.3979
By_Thorin_Klosowski           0.3880
By_Devin_Desjarlais           0.3858
By_Ily_Goyanes                0.3823
Rebecca_Haithcoat             0.3797
mond                          0.3786
Politicks                     0.3780
白                             0.3776
Michael_Colyar                0.3772
Htaw                          0.3770


Let us now check the similarity b/w a few pair of words


In [ ]:
# Example of calculating similarity
print(word_vectors.similarity('woman', 'man'))
print(word_vectors.similarity('king','queen'))
print(word_vectors.similarity('uncle','aunt'))
print(word_vectors.similarity('boy','girl'))
print(word_vectors.similarity('nephew','niece'))
print(word_vectors.similarity('paper','water'))
print(word_vectors.similarity('airplane','jet'))
print(word_vectors.similarity('duck','bird'))
# we can give different words to try it out



0.76640123
0.6510957
0.7643474
0.8543272
0.7594367
0.11408084
0.7161611
0.5125556


Most similar words from a given word

In [ ]:
print(word_vectors.most_similar("airplane", topn=5))

[('plane', 0.8348401784896851), ('airplanes', 0.7777001261711121), ('aircraft', 0.76496422290802), ('planes', 0.7335887551307678), ('jet', 0.7161610722541809)]


Now let us see the vector similarity

magnitude = the great size or extent of something or size.

In [ ]:
import numpy as np
# words to compare

word1 = 'man'
word2 = 'woman'

word3 = 'semiconductor'
word4 = 'earthworm'

word5 = 'nephew'
word6 = 'niece'

word7 = 'pirate'
word8  = 'mercenary'

# Calculate the vector difference
vector_difference1 = model[word1] - model[word2]
vector_difference2 = model[word3] - model[word4]
vector_difference3 = model[word5] - model[word6]
vector_difference4 = model[word7] - model[word8]


# Calculate the magnitutde of the vector difference

magnitude_of_difference1 = np.linalg.norm(vector_difference1)
magnitude_of_difference2 = np.linalg.norm(vector_difference2)
magnitude_of_difference3 = np.linalg.norm(vector_difference3)
magnitude_of_difference4 = np.linalg.norm(vector_difference4)


# Print the magnitude of the difference

print(
    "The magnitude of the difference between '{}' and '{}' is {:.2f}"
    .format(word1, word2, magnitude_of_difference1)
)

print(
    "The magnitude of the difference between '{}' and '{}' is {:.2f}"
    .format(word3, word4, magnitude_of_difference2)
)

print(
    "The magnitude of the difference between '{}' and '{}' is {:.2f}"
    .format(word5, word6, magnitude_of_difference3)
)

print(
    "The magnitude of the difference between '{}' and '{}' is {:.2f}"
    .format(word7, word8, magnitude_of_difference4)
)


The magnitude of the difference between 'man' and 'woman' is 1.73
The magnitude of the difference between 'semiconductor' and 'earthworm' is 5.67
The magnitude of the difference between 'nephew' and 'niece' is 1.96
The magnitude of the difference between 'pirate' and 'mercenary' is 3.89


In [ ]:
import torch

In [ ]:
input_ids = torch.tensor([11, 45, 31, 33, 90, 110, 220])


In [ ]:
vocab_size = 6
output_dim = 7

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [ ]:
gg = embedding_layer.weight

print(gg)


Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603, -0.2196],
        [-0.3792,  0.7671, -1.1925,  0.6984, -1.4097,  0.1794,  1.8951],
        [ 0.4954,  0.2692, -0.0770, -1.0205, -0.1690,  0.9178,  1.5810],
        [ 1.3010,  1.2753, -0.2010,  0.4965, -1.5723, -0.4845, -2.0929],
        [-0.8199, -0.4210, -0.9620,  1.2825,  0.8768,  1.6221, -0.9887],
        [-1.7018, -0.7498, -1.1285,  0.4135,  0.2892,  2.2473, -0.8036]],
       requires_grad=True)


In [ ]:
print(gg[3])


tensor([ 1.3010,  1.2753, -0.2010,  0.4965, -1.5723, -0.4845, -2.0929],
       grad_fn=<SelectBackward0>)


In [ ]:
print(gg[0])


tensor([ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603, -0.2196],
       grad_fn=<SelectBackward0>)


In [ ]:
print(embedding_layer(input_ids))


tensor([[ 0.4954,  0.2692, -0.0770, -1.0205, -0.1690,  0.9178,  1.5810],
        [ 1.3010,  1.2753, -0.2010,  0.4965, -1.5723, -0.4845, -2.0929],
        [-1.7018, -0.7498, -1.1285,  0.4135,  0.2892,  2.2473, -0.8036],
        [-0.3792,  0.7671, -1.1925,  0.6984, -1.4097,  0.1794,  1.8951]],
       grad_fn=<EmbeddingBackward0>)
